sudo: required
services:
  - docker

before_install:
  - docker build -t laurenchen/docker-react -f Dockerfile.dev .

script:
  - docker run laurenchen/docker-react npm run test ----coverage
  # - docker run -e CI=true laurenchen/docker-react npm run test
  # script:
  # - docker run -e CI=true USERNAME/docker-react npm run test
  # language: generic 